<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">
    
    <joint name="camera_joint" type="fixed">
            <parent link="chassis"/>
            <child link="camera_link"/>
            <origin xyz="${(chassis_length/2)+(camera_x/2)} 0 ${chassis_height/2}" rpy="0 0 0"/>
        </joint>

        <link name="camera_link">
            <visual>
                <geometry>
                    <box size="${camera_x} ${camera_y} ${camera_z}"/>
                </geometry>
                <material name="Gray">
                    <color rgba="0.5 0.5 0.5 1.0"/>
                </material>
            </visual>
        <xacro:inertial_box mass=".7" x="${camera_x}" y="${camera_y}" z="${camera_z}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_box>
        </link>


        <joint name="camera_optical_joint" type="fixed">
            <parent link="camera_link"/>
            <child link="camera_link_optical"/>
            <origin xyz="0 0 0" rpy="${-pi/2} 0 ${-pi/2}"/>
        </joint>

        <link name="camera_link_optical"></link>



        <gazebo reference="camera_link">
            <material>Gazebo/Red</material>

            <sensor name="camera" type="camera">
                <pose> 0 0 0 0 0 0 </pose>
                <visualize>true</visualize>
                <update_rate>10</update_rate>
                <camera>
                    <horizontal_fov>${camera_fov}</horizontal_fov>
                    <image>
                        <format>R8G8B8</format>
                        <width>640</width>
                        <height>480</height>
                    </image>
                    <clip>
                        <near>0.05</near>
                        <far>8.0</far>
                    </clip>
                </camera>
                <plugin name="camera_controller" filename="libgazebo_ros_camera.so">
                    <frame_name>camera_link_optical</frame_name>
                </plugin>
            </sensor>   
        </gazebo>
        
        
</robot>