<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">
    
    
    <joint name="lidar_joint" type="fixed">
            <parent link="chassis"/>
            <child link="lidar_link"/>
            <origin xyz="0 0 ${chassis_height+(imu_height/2)}" rpy="0 0 0"/>
    </joint>

    <link name="lidar_link">
        <visual>
            <geometry>
                <cylinder radius="${lidar_radius}" length="${lidar_length}"/>
            </geometry>
            <material name="Gray">
                <color rgba="0.5 0.5 0.5 1.0"/>
            </material>
        </visual>
        <xacro:inertial_cylinder mass="0.1" length="0.04" radius="0.05">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>
    

    <gazebo reference="lidar_link">
        <sensor name="laser" type="ray">
            <always_on>true</always_on>
            <visualize>false</visualize>
            <pose>0.0 0 0.0 0 0 0</pose>
            <update_rate>10</update_rate>
            <ray>
                <scan>
                    <horizontal>
                    <samples>360</samples>
                    <resolution>1</resolution>
                    <min_angle>-1.57</min_angle>
                    <max_angle>1.57</max_angle>
                    </horizontal>
                </scan>
                <range>
                    <min>0.3</min>
                    <max>12</max>
                    <resolution>0.01</resolution>
                </range>
            </ray>
            <plugin name="laser_controller" filename="libgazebo_ros_ray_sensor.so">
                <ros>
                    <remapping>~/out:=/scan</remapping>
                </ros>
                <output_type>sensor_msgs/LaserScan</output_type>
                <frame_name>lidar_link</frame_name>
            </plugin>
        </sensor>
    </gazebo>

</robot>