<?xml version="1.0"?>
<robot name="sec_bot" xmlns:xacro="http://ros.org/wiki/xacro">

    <!-- Define robot constants -->
    <!-- Unit -->
    <xacro:property name="chassis_length" value="0.5"/> <!--X-->
    <xacro:property name="chassis_width" value="0.5"/> <!--Y-->
    <xacro:property name="chassis_height" value="0.5"/> <!--Z-->
    <xacro:property name="chassis_mass" value="10"/>

    <xacro:property name="wheel_radius" value="0.1"/>
    <xacro:property name="wheel_length" value="0.1"/>
    <xacro:property name="wheel_height_offset" value="0.03"/>
    <xacro:property name="wheel_mass" value="10"/>


    <!-- The difference between bottom middle of chassis and wheel position(s)-->
    <xacro:property name="wheel_x_displacement" value="${chassis_length/4}"/>
    <xacro:property name="wheel_y_displacement" value="${chassis_width/2+wheel_radius/2}"/>
    <xacro:property name="wheel_z_displacement" value="0.03"/>

    <xacro:include filename="robot_core.xacro"/>
    <xacro:include filename="gazebo_control.xacro"/>
    
</robot>