<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <gazebo>
        <plugin name="skid_steer_drive_controller" filename="libgazebo_ros_skid_steer_drive.so">
            <updateRate>100.0</updateRate>
            <robotNamespace>/</robotNamespace>
            <leftFrontJoint>f_l_wheel_joint</leftFrontJoint>
            <rightFrontJoint>f_r_wheel_joint</rightFrontJoint>
            <leftRearJoint>b_l_wheel_joint</leftRearJoint>
            <rightRearJoint>b_r_wheel_joint</rightRearJoint>
            <wheelSeparation>${chassis_length}</wheelSeparation>
            <wheelDiameter>${wheel_radius*2}</wheelDiameter>
            <robotBaseFrame>base_link</robotBaseFrame>
            <torque>20</torque>
            <topicName>cmd_vel</topicName>
            <broadcastTF>true</broadcastTF>
        </plugin>
    </gazebo>

    <gazebo>
        <plugin name="four_wheeled_robot_diff_drive" filename="libgazebo_ros_skid_steer_drive.so">

            <!-- Number of wheel pairs -->
            <num_wheel_pairs>2</num_wheel_pairs>

            <!-- wheels0 -->
            <left_joint>f_l_wheel_joint</left_joint>
            <right_joint>f_r_wheel_joint</right_joint>

            <!-- wheels1-->
            <left_joint>b_l_wheel_joint</left_joint>
            <right_joint>b_r_wheel_joint</right_joint>

            <!-- kinematics -->
            <wheel_separation>"${chassis_width}"</wheel_separation>
            <wheel_separation>"${chassis_width}"</wheel_separation>

            <wheel_diameter>${wheel_radius*2}</wheel_diameter>
            <wheel_diameter>${wheel_radius*2}</wheel_diameter>

            <!-- limits -->
            <max_wheel_torque>200</max_wheel_torque>
            <max_wheel_acceleration>10.0</max_wheel_acceleration>

            <!-- output -->
            <publish_odom>true</publish_odom>
            <publish_odom_tf>true</publish_odom_tf>
            <publish_wheel_tf>true</publish_wheel_tf>

            <odometry_frame>odom</odometry_frame>
            <robot_base_frame>base_link</robot_base_frame>
        </plugin>
    </gazebo>

</robot>